Repository GalaxyInit/TUI-For-Everyone, pull requests merged in 2022-10, with the labels that each got.

#49 Added Insta Check
  Neelesh/Minion.py
  Neelesh/insta.py
  Neelesh/merge_the_tools.py
Labels: hacktoberfest-accepted

#50 added stack
  DSA/stack.cpp
Labels: hacktoberfest

#51 added new file
  mine/1st file
Labels: hacktoberfest

#53 added 2nd file
  mine/2nd file
Labels: hacktoberfest, hacktoberfest-accepted

#54 added 3 file
  mine/3file
Labels: hacktoberfest, hacktoberfest-accepted

#55 added 4th file
  mine/4file
Labels: hacktoberfest, hacktoberfest-accepted

#56 5 file added
  mine/5th file
Labels: hacktoberfest, hacktoberfest-accepted

#58 cleantext lib
  python-libs/cleantext.py
Labels: hacktoberfest, hacktoberfest-accepted

#61 emoji lib
  python-libs/emoji.py
Labels: hacktoberfest, hacktoberfest-accepted

#60 Vp json pr
  python-libs/json.py
Labels: hacktoberfest, hacktoberfest-accepted

#59 pillow library
  python-libs/pillow.py
Labels: hacktoberfest, hacktoberfest-accepted

#57 Structure Change
  Code/AutomatedChromeDinosaur.py
  Code/LICENSE
  Code/Minion.py
  Code/README.md
  Code/Readme1.md
  Code/insta.py
  Code/jarvis
  Code/main.py
  Code/merge_the_tools.py
  Code/passmanager
  Code/requirements.txt
  Code/requirements11.txt
  Code/screen.py
  Code/settings.py
Labels: hacktoberfest, hacktoberfest-accepted

#62 AStar Added
  Neelesh/Astar.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#63 UglyNumbers.cpp
  newHack/UglyNumbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#66 Word Break.cpp
  Word Break
Labels: hacktoberfest, hacktoberfest-accepted

#65 DiceThrow.cpp
  newHack/Dice Throw
Labels: hacktoberfest, hacktoberfest-accepted

#64 EggDroppingPuzzle.cpp
  newHack/Egg Dropping
Labels: hacktoberfest, hacktoberfest-accepted

#71 Longest Common Substring
  NHack/Longest Common Substring
Labels: hacktoberfest, hacktoberfest-accepted

#70 Maximum Product Cutting
  NHack/Maximum Product Cutting
Labels: hacktoberfest, hacktoberfest-accepted

#69 Coin Change
  NHack/Coin Change
Labels: hacktoberfest, hacktoberfest-accepted

#68 EditDistance
  NHack/Edit Distance
Labels: hacktoberfest, hacktoberfest-accepted

#91 done
  Another file
Labels: hacktoberfest, hacktoberfest-accepted

#90 changes
  Adimanipr3
Labels: hacktoberfest, hacktoberfest-accepted

#89 delete
  daddy
Labels: hacktoberfest, hacktoberfest-accepted

#87 update automatedchrome
  Neelesh/AutomatedChromeDinosaur.py
Labels: hacktoberfest, hacktoberfest-accepted

#86 linked list.cpp
  tej.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#85 added graph
  DSA/graph.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#84 added some code and comments
  Neelesh/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#83 heap
  DSA/heap
Labels: hacktoberfest, hacktoberfest-accepted

#82 observation
  Tranpose_matrix.py
Labels: hacktoberfest, hacktoberfest-accepted

#81 ALGO
  ALGO
  summer training program
Labels: hacktoberfest, hacktoberfest-accepted

#80 added code and changes
  Neelesh/insta.py
Labels: hacktoberfest, hacktoberfest-accepted

#78 added code and comments
  Adimanipr05
  mai tera hero
Labels: hacktoberfest, hacktoberfest-accepted

#77 insertion deletion
  Tranpose_matrix.py
  array.cpp
  reverse_string.py
Labels: hacktoberfest, hacktoberfest-accepted

#76 added code
  max sub arr.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#75 one line
  Adimanipr2
Labels: hacktoberfest, hacktoberfest-accepted

#74 22
  DSA/Bubble Sort.cpp
  Docker/Bubble Sort.cpp
  Docker/Heap_sort.py
  Docker/TOI.py
  Docker/main.py
  Docker/stack.cpp
  adimani
Labels: hacktoberfest, hacktoberfest-accepted

#157 aditya
  aditya
Labels: hacktoberfest, hacktoberfest-accepted

#156 demo
  demo22
Labels: hacktoberfest, hacktoberfest-accepted

#155 commit
  bubble_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#154 tarun4
  sat/tarun4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#153 tarun3
  sat/tarun3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#152 tarun2
  sat/tarun2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#151 tarun1
  sat/tarun1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#148 priya2
  sat/priya2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#147 priya1
  sat/Priya1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#146 swati4
  sat/swati4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#145 swati3
  sat/swati3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#144 swati2
  swati2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#143 swati1
  swati1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#142 4
  sat/4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#159 SGHSR
  afdhbadfbsFghq4hWRG
Labels: hacktoberfest, hacktoberfest-accepted

#160 RJTKLER
  LGLWFLKDSK
Labels: hacktoberfest, hacktoberfest-accepted

#161 SBDBDWDN
  WMFLWJENRFLWEN
Labels: hacktoberfest, hacktoberfest-accepted

#162 DNGFBDKNFBJSD
  34JRLENSDL
Labels: hacktoberfest, hacktoberfest-accepted

#163 added vaish
  vaish1
Labels: hacktoberfest, hacktoberfest-accepted

#164 added 2nd vaish
  vaish2
Labels: hacktoberfest, hacktoberfest-accepted

#165 added vaish 3
  vaish3
Labels: hacktoberfest, hacktoberfest-accepted

#166 added4th
  vaish4
Labels: hacktoberfest, hacktoberfest-accepted

#167 added 1pr
  shiva1
Labels: hacktoberfest, hacktoberfest-accepted

#96 added new code
  ALGO
  Another file
  DS/main.cpp
  Neelesh/New Text Document.txt
Labels: hacktoberfest, hacktoberfest-accepted

#92 hello
  hello.py
Labels: hacktoberfest, hacktoberfest-accepted

#116 adding 4th time
  anshulfour
Labels: hacktoberfest, hacktoberfest-accepted

#115 add numbers
  Neelesh/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#114 Update Minion.py
  Neelesh/Minion.py
Labels: hacktoberfest, hacktoberfest-accepted

#112 still adding the codes
  anshulthird
Labels: hacktoberfest, hacktoberfest-accepted

#111 Binary cpp
  DSA/binary.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#110 added insertion sort code
  insertionsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#109 Added code
  DSA/merge.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#108 2002
  hash_of_file.py
Labels: hacktoberfest, hacktoberfest-accepted

#107 added name
  Neelesh/insta.py
Labels: hacktoberfest, hacktoberfest-accepted

#106 Branch001
  DSA/linearsearch.cpp
  Neelesh/insta.py
Labels: hacktoberfest, hacktoberfest-accepted

#105 adding new code
  anshulsecond
Labels: hacktoberfest, hacktoberfest-accepted

#104 added new code of bubble sort
  bubblesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#102 added binary search code
  binarysearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#100 Added a new code
  Neelesh/Minion.py
Labels: hacktoberfest, hacktoberfest-accepted

#98 new file
  1.cpp
  Adimanipr2
Labels: hacktoberfest, hacktoberfest-accepted

#97 added selection sort code
  code.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#95 Added new code of linked list.
  Dsa.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#94 added hello everyone
  Client_frontend/anshul
Labels: hacktoberfest, hacktoberfest-accepted

#93 Create ak.cpp
  ak.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#117 graph
  DSA/graph2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#118 Create gitt.cpp
  gitt.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#119 Create hub.cpp
  hub.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#120 New code added
  Neelesh/merge_the_tools.py
Labels: hacktoberfest, hacktoberfest-accepted

#121 Screen on
  Neelesh/screen.py
Labels: hacktoberfest, hacktoberfest-accepted

#125 Added new line
  Neelesh/insta.py
Labels: hacktoberfest, hacktoberfest-accepted

#130 change
  Docker/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#141 3
  sat/3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#140 5
  Code/screen.py
  adimani
Labels: hacktoberfest, hacktoberfest-accepted

#138 3
  3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#137 2
  sat/2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#135 ch4
  DSA/graph.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#129 not
  sat/not.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#127 Create what.cpp
  sat/what.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#128 why
  sat/why.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#126 how
  sat/how.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#124 gg
  sat/gg.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#123 hello
  sat/hello.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#122 hey
  sat/hey.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#113 hii
  sat/hii.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#168 jeet
  sat/jeet.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#170 added
  adimani
Labels: hacktoberfest, hacktoberfest-accepted

#172 Create grv.cpp
  grv.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#173 Create yugyt.cpp
  yugyt.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#176 Create QWERERS.CPP
  QWERERS.CPP
Labels: hacktoberfest, hacktoberfest-accepted

#177 Create gugiuh.cpp
  gugiuh.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#178 Create Y53WTR.CPP
  Y53WTR.CPP
Labels: hacktoberfest, hacktoberfest-accepted

#179 Create WC.CPP
  WC.CPP
Labels: hacktoberfest, hacktoberfest-accepted

#181 mon
  sat/mon.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#182 sun
  sat/sun.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#183 Create giuhoi.cpp
  giuhoi.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#184 tue
  sat/tue.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#196 Create b4.cpp
  b4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#195 Create b3.cpp
  b3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#194 Create b2.cpp
  b2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#193 Create b1.cpp
  b1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#192 Create get4.cpp
  get4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#191 Create get3.cpp
  get3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#190 Create get2.cpp
  get2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#189 Create get1.cpp
  get1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#187 Create new3.cpp
  new3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#186 Create new2.cpp
  new2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#185 Create new1.cpp
  new1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#200 Yo2
  hack1/Yo2
Labels: hacktoberfest, hacktoberfest-accepted

#199 HeLlo1
  hack1/HeLlo1
Labels: hacktoberfest, hacktoberfest-accepted

#198 Hi2
  hack1/Hi2
Labels: hacktoberfest, hacktoberfest-accepted

#197 hi1
  hack1/hi1
Labels: hacktoberfest, hacktoberfest-accepted

#205 Create 101.py
  101.py
Labels: hacktoberfest, hacktoberfest-accepted

#207 Create 103.py
  103.py
Labels: hacktoberfest, hacktoberfest-accepted

#208 Create 104.py
  104.py
Labels: hacktoberfest, hacktoberfest-accepted

#204 s4
  sat/s4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#203 s3
  sat/s3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#202 s2
  sat/s2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#201 s1
  sat/s1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#209 Create cherry.py
  Neelesh/cherry.py
Labels: hacktoberfest, hacktoberfest-accepted

#210 Create cherry2.py
  Neelesh/cherry2.py
Labels: hacktoberfest, hacktoberfest-accepted

#211 Create cherry3,py
  cherry3,py
Labels: hacktoberfest, hacktoberfest-accepted

#212 Create cherry4.py
  Neelesh/cherry4.py
Labels: hacktoberfest, hacktoberfest-accepted

#216 Create hello4.py
  Do_make_your_own_folder/hello4.py
Labels: hacktoberfest, hacktoberfest-accepted

#215 Create hello3.py
  Do_make_your_own_folder/hello3.py
Labels: hacktoberfest, hacktoberfest-accepted

#214 Create hello2.py
  Do_make_your_own_folder/hello2.py
Labels: hacktoberfest, hacktoberfest-accepted

#213 Create hello1.py
  Do_make_your_own_folder/hello1.py
Labels: hacktoberfest, hacktoberfest-accepted

#220 Create k4.cpp
  hack1/k4.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#219 Create k3.cpp
  hack1/k3.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#218 Create k2.cpp
  hack1/k2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#217 Create k1.cpp
  hack1/k1.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#242 Create Box.mail
  Box.mail
Labels: hacktoberfest, hacktoberfest-accepted

#241 Create Follow.c
  DSA/Follow.c
Labels: hacktoberfest, hacktoberfest-accepted

#240 Create Main1.py
  DSA/Main1.py
Labels: hacktoberfest, hacktoberfest-accepted
